version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: apace-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: apace_db
      MYSQL_USER: apace_user
      MYSQL_PASSWORD: apace_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
