version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: apace-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: apace_db
      MYSQL_USER: apace_user
      MYSQL_PASSWORD: apace_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - apace-network

  redis:
    image: redis:7-alpine
    container_name: apace-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5
    networks:
      - apace-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apace-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=apace_user
      - DATABASE_PASSWORD=apace_password
      - DATABASE_NAME=apace_db
      - JWT_SECRET=your_jwt_secret_key_change_this
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_key_change_this
      - JWT_EXPIRES_IN=24h
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_ENABLED=true
      - CACHE_TTL_DEFAULT=300
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - apace-network
    command: >
      sh -c "
        echo 'Waiting for database and Redis...' &&
        sleep 10 &&
        npm run db:migrate &&
        npm run db:seed &&
        node server.js
      "

  admin-panel:
    build:
      context: ./AdminPanel
      dockerfile: Dockerfile
    container_name: apace-admin
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - apace-network

networks:
  apace-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: