version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: apace-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-prodRootPass2024!}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-apace_db}
      MYSQL_USER: ${MYSQL_USER:-apace_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-prodApacePass2024!}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - apace-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    image: gcr.io/ayush-bot/apace-backend:latest
    container_name: apace-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3307
      - DATABASE_USER=${MYSQL_USER:-apace_user}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD:-prodApacePass2024!}
      - DATABASE_NAME=${MYSQL_DATABASE:-apace_db}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1h}
      - REFRESH_TOKEN_EXPIRES_IN=${REFRESH_TOKEN_EXPIRES_IN:-7d}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://34.44.169.87}
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - apace-network
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 15 &&
        npm run db:migrate &&
        npm run db:seed &&
        node server.js
      "

  admin-panel:
    image: gcr.io/ayush-bot/apace-admin:latest
    container_name: apace-admin
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://34.44.169.87:5000
    networks:
      - apace-network

networks:
  apace-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local